rule all:
    input:
        "figure.png"


rule plot:
    input:
        data="decay_observed.csv",
        script="plot.py"
    output:
        "figure.png"
    shell:
        "python {input.script}"
        